### ISSUE TITLE
Format "-%s %v" is impossible for now. 

### ISSUE THREAD

**Issue by vihryn** [cibernox/ember-cli-accounting#14]
I need this format, but it can't be, cause in checkCurrencyFormat method use format "%s -%v".

**Comment by cibernox** [comment]
This addon is a thin wrapper around accounting.js. 
If `{{format-money someNumber format="-%s %v"}}` doesn't work for you because accounting.js considers that format invalid I'd rather advice you to report it as a bug in accounting.js itself and as soon as they release a new version let me know and I'll update the addon to the latest version.

**Comment by vihryn** [comment]
In accounting.js I can set format by object with negative format in settings  ``` neg : "-%s %v" ```. And it works fine for me. How can I repeat it with this addon?

[docs](http://openexchangerates.github.io/accounting.js/#documentation)

**Comment by cibernox** [comment]
I must have misunderstood your issue then. You want to set the global configuration for negative numbers. You can set the global configuration using an initializer by example:

https://github.com/cibernox/ember-cli-accounting/blob/master/tests/dummy/app/initializers/accounting.js

Does that work for you?

**Comment by vihryn** [comment]
Yes, it works. Thanks.
